# Generated by Django 4.2.3 on 2023-07-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gapp.product'),
            preserve_default=False,
        ),
    ]
